### ISSUE TITLE
Textbox sample text is inserted instead of being a hint on Payment Info Page.

### ISSUE THREAD

**Issue by Torboto** [gcoomber/TextCrunch#19]
Text in textboxes should be hints so that the text disappears when you start typing. This happens on the Payment Info page, see screenshot: http://d.pr/i/11nIm

**Comment by diego04** [comment]
yes, there will be a push tonight for this

**Comment by Torboto** [comment]
Hm, I have to tie it into the backend to have it ready for tomorrow. I'll
just do it in my branch, don't worry about it. =)

**Comment by diego04** [comment]
OK,  cool thanks!
