### ISSUE TITLE
duplicate rows in the database

### ISSUE THREAD

**Issue by diego04** [gcoomber/TextCrunch#38]
so im looking to add locations to each book and i noticed we're duplicating rows in the book table. i'll try to fix this at the end of the sprint.

**Comment by hpabst** [comment]
Running the tests creates mock books in the database. Sure you're not looking at those?

**Comment by diego04** [comment]
Yeah, Ive just recently looked at the test code. Its in my scope of work. it happens somewhere in the edit listing view controller or listing view controller. I'll have to fix this. Just wanted to give you guys a heads up

**Comment by Torboto** [comment]
Merged with other db bugs
