### ISSUE TITLE
"Invalid Password" on Registration

### ISSUE THREAD

**Issue by derekdowling** [gcoomber/TextCrunch#56]
I get an "invalid password" error when trying to create a new user when really my password is to short. This is super misleading and should get updated so we don't loose people at signup.

**Comment by ZaneH** [comment]
Is this issue still relevant? While checking the source for where this error would occur I found something that looks like a fix: https://github.com/gcoomber/TextCrunch/blob/master/TextCrunch/AccountCreationViewController.swift#L61

**Comment by Torboto** [comment]
Add a "8 char min" label/error something.

**Comment by hpabst** [comment]
There is now a label indicating the minimum password length.
