### ISSUE TITLE
Duplicate books in parse db.

### ISSUE THREAD

**Issue by gcoomber** [gcoomber/TextCrunch#61]
When a user scans a UPC or enters an isbn, the found book is added to the parse db regardless of if a matching book already exists in the DB. If a book already exists in the db, its info should be retrieved rather than making a dupe DB entry.

**Comment by Torboto** [comment]
Books are added to parse db before user confirms listing

**Comment by derekdowling** [comment]
Check if this book can be queried by ISBN from Parse before performing a lookup.
