### ISSUE TITLE
TableView Inconsistencies

### ISSUE THREAD

**Issue by Torboto** [gcoomber/TextCrunch#92]
The TableView on the Search page is very different (different sized items, image size, formatting) from the TableView that shows the exact same information on the Listings page. They should be identical.

Books are rectangular, and should be displayed in a rectangular box rather than being stretched into squares.

**Comment by gcoomber** [comment]
Henry if you have time, would you be able to look at this? I think this was your screen

**Comment by Torboto** [comment]
DID IT. :bomb:
