### ISSUE TITLE
Update/Create Listing Button States

### ISSUE THREAD

**Issue by Torboto** [gcoomber/TextCrunch#94]
On EditListingView the Update button should only show when accessing from ViewListing, Create Listing button should only show when accessed from ISBNView.

**Comment by gcoomber** [comment]
Yeah, this needs to be fixed. Should be an easy fix by adding a flag and hiding a button on specific segues

**Comment by gcoomber** [comment]
The layout seems to have hidden this issue. AKA it fixed itself? Closing
