### ISSUE TITLE
Camera Crash

### ISSUE THREAD

**Issue by Torboto** [gcoomber/TextCrunch#97]
App crashes when I click 'Take A Photo' while creating listing in emulator.

2015-04-06 04:34:36.129 TextCrunch[69660:17151028] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Source type 1 not available'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110fbea75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000011143bbb7 objc_exception_throw + 45
	2   UIKit                               0x000000010fe4d60a -[UIImagePickerController sourceType] + 0
	3   TextCrunch                          0x000000010d45f3a1 _TFC10TextCrunch25TakePictureViewController9takePhotofS0_FPSs9AnyObject_T_ + 817
	4   TextCrunch                          0x000000010d45f976 _TToFC10TextCrunch25TakePictureViewController9takePhotofS0_FPSs9AnyObject_T_ + 54
	5   UIKit                               0x000000010fbb0a22 -[UIApplication sendAction:to:from:forEvent:] + 75
	6   UIKit                               0x000000010fcb7e50 -[UIControl _sendActionsForEvents:withEvent:] + 467
	7   UIKit                               0x000000010fcb721f -[UIControl touchesEnded:withEvent:] + 522
	8   UIKit                               0x000000010fbf6b68 -[UIWindow _sendTouchesForEvent:] + 735
	9   UIKit                               0x000000010fbf7493 -[UIWindow sendEvent:] + 683
	10  UIKit                               0x000000010fbc3fb1 -[UIApplication sendEvent:] + 246
	11  UIKit                               0x000000010fbd1227 _UIApplicationHandleEventFromQueueEvent + 17700
	12  UIKit                               0x000000010fbac23c _UIApplicationHandleEventQueue + 2066
	13  CoreFoundation                      0x0000000110ef3c91 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	14  CoreFoundation                      0x0000000110ee9b5d __CFRunLoopDoSources0 + 269
	15  CoreFoundation                      0x0000000110ee9194 __CFRunLoopRun + 868
	16  CoreFoundation                      0x0000000110ee8bc6 CFRunLoopRunSpecific + 470
	17  GraphicsServices                    0x0000000112c6da58 GSEventRunModal + 161
	18  UIKit                               0x000000010fbaf580 UIApplicationMain + 1282
	19  TextCrunch                          0x000000010d424e6e top_level_code + 78
	20  TextCrunch                          0x000000010d424f4a main + 42
	21  libdyld.dylib                       0x0000000111c17145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hpabst** [comment]
This is because the emulator doesn't have a camera, hence why we needed to use a device to get images working. We could catch the exception and display a UIAlert telling the user they need to use a camera to take a picture?

**Comment by gcoomber** [comment]
Yeah, not sure this is an actual bug
